### PR TITLE
Implement anisotropic properties_container.

### LINKED ISSUE #251: Move and implement anisotropic specfem::compute::impl::properties_container  to specfem::medium::compute_properties
- [ ] Move isotropic properties_container
- [ ] Implement anisotropic properties_container

### PR DESCRIPTION
**Pull request by icui**
# Description

Implement anisotropic properties_container.

# Issue Number

Closes #251

# Checklist

Please make sure to check developer documentation on specfem docs. 

[] I ran the code through pre-commit to check style
[] My code passes all the integration tests
[] I have added sufficient unittests to test my changes
[] I have added/updated documentation for the changes I am proposing
[] I have updated CMakeLists to ensure my code builds
[] My code builds across all platforms

### CODE REVIEW

**Comment by Rohit-Kakodkar** [comment]
We will also need to update `src/compute_properties.cpp` to add elastic isotropic properties during construction of `specfem::compute::properties`

**Review by lsawade — APPROVED** [review]
LGTM

**Comment by lsawade** [comment]
> We will also need to update `src/compute_properties.cpp` to add elastic isotropic properties during construction of `specfem::compute::properties`

Are you doing this as part of this issue, @icui ? 
Maybe open another one or mention this in #228.

**Comment by icui** [comment]
> > We will also need to update `src/compute_properties.cpp` to add elastic isotropic properties during construction of `specfem::compute::properties`
> 
> Are you doing this as part of this issue, @icui ? Maybe open another one or mention this in #228.

I'm working on it.

**Comment by icui** [comment]
> > We will also need to update `src/compute_properties.cpp` to add elastic isotropic properties during construction of `specfem::compute::properties`
> 
> Are you doing this as part of this issue, @icui ? Maybe open another one or mention this in #228.

Now updated. I'm merged branch issue-250 in order to compile.

**Review by Rohit-Kakodkar — APPROVED** [review]
LGTM

**Pull request merged**
