### PR TITLE
Implement kernels_container

### LINKED ISSUE #274: `include/compute/kernels/kernels.hpp`

### PR DESCRIPTION
**Pull request by icui**
# Description

Implement kernels_container

# Issue Number

Closes #274 and #275

# Checklist

Please make sure to check developer documentation on specfem docs. 

[] I ran the code through pre-commit to check style
[] My code passes all the integration tests
[] I have added sufficient unittests to test my changes
[] I have added/updated documentation for the changes I am proposing
[] I have updated CMakeLists to ensure my code builds
[] My code builds across all platforms

### CODE REVIEW

**Review by Rohit-Kakodkar — APPROVED** [review]
LGTM

**Review by Rohit-Kakodkar — CHANGES_REQUESTED** [review]
Can you update the tests in `tests/unit-tests/assembly/kernels` to include poroelastic domains?

**Review by lsawade — APPROVED** [review]
LGTM

**Review by Rohit-Kakodkar — APPROVED** [review]
LGTM

**Comment by icui** [comment]
> Can you update the tests in `tests/unit-tests/assembly/kernels` to include poroelastic domains?

Added. But the tests requires `frechert_derivatives/element_kernel` to be updated.

**Pull request merged**
