### PR TITLE
Implements test for `specfem::mesh::materials`

### LINKED ISSUE #264: Add test to check whether the properties are correctly assigned.
Add a unit-tests, that checks whether `specfem::materials::properties` has been read correctly. 

This can be adapted to other "test" meshes

### PR DESCRIPTION
**Pull request by Rohit-Kakodkar**
# Description

Implements #264

These tests use [Google test fixture](https://google.github.io/googletest/primer.html#same-data-multiple-tests)

 - The `MESH` test fixture in  `test_fixture.hpp` is used to hold all the meshes defined in `test_config.yaml `.
 - Within `tests/unit-tests/mesh/materials/materials.cpp` I check that every spectral element in the mesh is assigned the correct material properties. The correct material properties are defined in `static` variable `ground_truth`.

# Issue Number

Closes #264

# Checklist

Please make sure to check developer documentation on specfem docs. 

- [x] I ran the code through pre-commit to check style
- [ ] My code passes all the integration tests
- [x] I have added sufficient unittests to test my changes
- [x] I have added/updated documentation for the changes I am proposing
- [x] I have updated CMakeLists to ensure my code builds
- [x] My code builds across all platforms

### CODE REVIEW

**Comment by icui** [comment]
Do you want to merge #250 to 228 first?

**Comment by Rohit-Kakodkar** [comment]
> Do you want to merge #250 to 228 first?

Done

**Review by icui — APPROVED** [review]
LGTM

**Review by lsawade — APPROVED** [review]
LGTM

**Pull request merged**
