### PR TITLE
Fix for Apple clang compilation

### PR DESCRIPTION
**Pull request by lsawade**
# Description

# Issue Number

Adresses tracking issue and subtasks.

- #155
  + #152 
  + #153  

# Additionals

- Updated the issue template to include the spaces required for the checklist because I got frustrated.
- Added line to compiler support table in the getting started section of the documentation.

# Checklist

Please make sure to check developer documentation on specfem docs. 

- [x] I ran the code through pre-commit to check style
- [x] My code passes all the integration tests
- [ ] I have added sufficient unittests to test my changes
- [ ] I have added/updated documentation for the changes I am proposing
- [ ] I have updated CMakeLists to ensure my code builds
- [ ] My code builds across all platforms

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by Rohit-Kakodkar** [comment]
yes, test this PR. @buildbot-princeton

**Comment by Rohit-Kakodkar** [comment]
retest this please

**Comment by Rohit-Kakodkar** [comment]
LGTM if the tests pass

**Pull request merged**
