### PR TITLE
Implements dimension specific axial and tangential elements

### LINKED ISSUE #207: Create templated class and specialization for `specfem::mesh::tangential_elements`

### LINKED ISSUE #208: Create templated class and specialization for `specfem::mesh::axial_elements`

### LINKED ISSUE #209: Create templated class and specialization for `specfem::mesh::materials`

### PR DESCRIPTION
**Pull request by lsawade**
# Description

Adds dimension flag to all

# Issue Number

closes #207, closes #208 

# Checklist

Please make sure to check developer documentation on specfem docs. 

- [x] I ran the code through pre-commit to check style
- [x] My code passes all the integration tests
- [x] I have added sufficient unittests to test my changes
- [x] I have added/updated documentation for the changes I am proposing
- [x] I have updated CMakeLists to ensure my code builds
- [x] My code builds across all platforms

### CODE REVIEW

**Comment by lsawade** [comment]
Closes #207

**Comment by lsawade** [comment]
resolves #207

**Comment by Rohit-Kakodkar** [comment]
retest this please

**Comment by Rohit-Kakodkar** [comment]
retest this please

**Review by Rohit-Kakodkar — APPROVED** [review]
LGTM

**Review by Rohit-Kakodkar — CHANGES_REQUESTED** [review]
Merge branch needs to change from `devel` to `issue-200`

**Comment by lsawade** [comment]
Changed the base. We should have done that from the start since 2 PR's were already merged into devel.

**Comment by Rohit-Kakodkar** [comment]
> Changed the base. We should have done that from the start since 2 PR's were already merged into devel.

ughh, agreed! Yeah I see control nodes was merged into `devel`. The parameters was merged into `issue-200`

**Comment by Rohit-Kakodkar** [comment]
Going to add a `review required before merge` guard on the devel branch. So github will explicitly require you to override the review process

**Review by Rohit-Kakodkar — APPROVED** [review]
LGTM

**Comment by lsawade** [comment]
hello

**Comment by lsawade** [comment]
retest this

**Comment by lsawade** [comment]
Tested locally. Merging.

**Pull request merged**
